-- MySQL Script generated by MySQL Workbench
-- Wed May 11 09:19:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lojabicicletas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lojabicicletas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojabicicletas` DEFAULT CHARACTER SET utf8 ;
USE `lojabicicletas` ;

-- -----------------------------------------------------
-- Table `lojabicicletas`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojabicicletas`.`Person` (
  `BusinessEntityID` INT NOT NULL,
  `PersonType` VARCHAR(45) NULL,
  `NameStyle` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  `FistName` VARCHAR(100) NULL,
  `MiddleName` VARCHAR(100) NULL,
  `LastName` VARCHAR(100) NULL,
  `Suffix` VARCHAR(45) NULL,
  `EmailPromotion` INT NULL,
  `AdditionalContactInfo` VARCHAR(2000) NULL,
  `Demographics` VARCHAR(2000) NULL,
  `rowguid` VARCHAR(150) NULL,
  `ModifiedDate` DATETIME NULL,
  PRIMARY KEY (`BusinessEntityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojabicicletas`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojabicicletas`.`Customer` (
  `CustomerID` INT NOT NULL,
  `PersonID` INT NULL,
  `StoreID` INT NULL,
  `TerritoryID` INT NULL,
  `AccountNumber` VARCHAR(150) NULL,
  `rowguid` VARCHAR(150) NULL,
  `ModifiedDate` DATETIME NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojabicicletas`.`SalesOrderHeader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojabicicletas`.`SalesOrderHeader` (
  `SalesOrderID` INT NOT NULL,
  `RevisionNumber` INT NULL,
  `OrderDate` DATETIME NULL,
  `DueDate` DATETIME NULL,
  `ShipDate` DATETIME NULL,
  `Status` INT NULL,
  `OnlineOrderFlag` TINYINT NULL,
  `SalesOrderNumber` VARCHAR(45) NULL,
  `PurchaseOrderNumber` VARCHAR(45) NULL,
  `AccountNumber` VARCHAR(45) NULL,
  `CustomerID` INT NULL,
  `SalesPersonID` INT NULL,
  `TerritoryID` INT NULL,
  `BillToAddressID` INT NULL,
  `ShipToAddressID` INT NULL,
  `ShipMethodID` INT NULL,
  `CreditCardApprovalCode` VARCHAR(150) NULL,
  `CurrencyRateID` INT NULL,
  `SubTotal` FLOAT NULL,
  `TaxAmt` FLOAT NULL,
  `Freight` FLOAT NULL,
  `TotalDue` FLOAT NULL,
  `Comment` VARCHAR(150) NULL,
  `rowguid` VARCHAR(150) NULL,
  `ModifiedDate` DATETIME NULL,
  PRIMARY KEY (`SalesOrderID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojabicicletas`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojabicicletas`.`Product` (
  `ProductID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `ProductNumber` VARCHAR(45) NULL,
  `MakeFlag` TINYINT NULL,
  `FinishedGoodsFlag` TINYINT NULL,
  `Color` VARCHAR(45) NULL,
  `SafetyStockLevel` INT NULL,
  `ReorderPoint` INT NULL,
  `StandardCost` FLOAT NULL,
  `ListPrice` FLOAT NULL,
  `Size` VARCHAR(45) NULL,
  `SizeUnitMeasureCode` VARCHAR(45) NULL,
  `WeightUnitMeasureCode` VARCHAR(45) NULL,
  `Weight` FLOAT NULL,
  `DaysToManufacture` INT NULL,
  `ProductLine` CHAR(1) NULL,
  `Class` CHAR(1) NULL,
  `Style` CHAR(1) NULL,
  `ProductSubcategoryID` INT NULL,
  `ProductModelID` INT NULL,
  `SellStartDate` DATETIME NULL,
  `SellEndDate` DATETIME NULL,
  `DiscontinuedDate` DATETIME NULL,
  `rowguid` VARCHAR(150) NULL,
  `ModifiedDate` DATETIME NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojabicicletas`.`SpecialOfferProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojabicicletas`.`SpecialOfferProduct` (
  `SpecialOfferID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `rowguid` VARCHAR(150) NULL,
  `ModifiedDate` DATETIME NULL,
  PRIMARY KEY (`SpecialOfferID`, `ProductID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojabicicletas`.`SalesOrderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojabicicletas`.`SalesOrderDetail` (
  `SalesOrderID` INT NOT NULL,
  `SalesOrderDetailID` INT NOT NULL,
  `CarrierTrackingNumber` VARCHAR(45) NULL,
  `OrderQty` INT NULL,
  `ProductID` INT NULL,
  `SpecialOfferID` INT NULL,
  `UnitPrice` FLOAT NULL,
  `UnitPriceDiscount` FLOAT NULL,
  `LineTotal` FLOAT NULL,
  `rowguid` VARCHAR(45) NULL,
  `ModifiedDate` DATETIME NULL,
  PRIMARY KEY (`SalesOrderID`,`SalesOrderDetailID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
